export const GET_COURSE_DATA = `GET_COURSE_DATA`;
export const GET_COURSE_DATA_DONE = `GET_COURSE_DATA_DONE`;
export const GET_COURSE_DATA_FAIL = `GET_COURSE_DATA_FAIL`;

export const CLEAR_COURSE_DATA = `CLEAR_COURSE_DATA`;
