export const MAKE_HTTP_REQUEST = `MAKE_HTTP_REQUEST`;
export const MAKE_HTTP_REQUEST_DONE = `MAKE_HTTP_REQUEST_DONE`;
export const MAKE_HTTP_REQUEST_FAIL = `MAKE_HTTP_REQUEST_FAIL`;

export const GET_API_TOKEN = `GET_API_TOKEN`;
export const GET_API_TOKEN_DONE = `GET_API_TOKEN_DONE`;
export const GET_API_TOKEN_FAIL = `GET_API_TOKEN_FAIL`;
