export const GET_COURSES_OVERVIEW = `GET_COURSES_OVERVIEW`;
export const GET_COURSES_OVERVIEW_DONE = `GET_COURSES_OVERVIEW_DONE`;
export const GET_COURSES_OVERVIEW_FAIL = `GET_COURSES_OVERVIEW_FAIL`;
